apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
    name: {{ .Release.Name }}-issuer
spec:
    acme:
        # The ACME server URL
        server: https://acme-v02.api.letsencrypt.org/directory
        # Email address used for ACME registration
        email: {{ .Values.sulu.ingress.tls.email }}
        # Name of a secret used to store the ACME account private key
        privateKeySecretRef:
            name: {{ .Values.sulu.ingress.tls.secretName }}-tls
        # Enable the HTTP-01 challenge provider
        http01: {}
